# A comprehensive GitHub Actions workflow to build and test Python wheels for multiple
# platforms and architectures using a matrix strategy.
# It supports both manylinux (glibc-based) and musllinux (musl-based) wheels
# on x86_64 and aarch64 architectures.

name: build-all-opengrep-wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # This job runs on the host to prepare the repository and get the latest release tag.
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_release.outputs.tag }}
    steps:
      - name: Get latest release tag
        id: get_release
        run: |
          tag=$(curl -s https://api.github.com/repos/opengrep/opengrep/releases/latest | jq -r .tag_name)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Make checkout speedy
        run: git config --global fetch.parallel 50

      - name: Checkout source at release tag
        # This is a host-based action, which is fine in a separate job.
        uses: actions/checkout@v4
        with:
          submodules: true
          repository: opengrep/opengrep
          ref: ${{ steps.get_release.outputs.tag }}
      
      # Upload the entire checked out repository as a build artifact.
      - name: Upload source as artifact
        uses: actions/upload-artifact@v4
        with:
          name: opengrep-source
          path: .
          
  build-and-test-wheels:
    name: Build & Test ${{ matrix.os_type }}-${{ matrix.arch }}
    # This job runs on the host to ensure compatibility with JavaScript-based actions.
    runs-on: ${{ matrix.arch == 'x86_64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    needs: prepare
    
    strategy:
      # The build matrix defines all combinations to be run.
      fail-fast: false
      matrix:
        os_type: ["manylinux", "musllinux"]
        arch: ["x86_64", "aarch64"]

    steps:
      - name: Download source artifact
        # This action must run on the host runner
        uses: actions/download-artifact@v4
        with:
          name: opengrep-source
          path: .

      - name: Run in ${{ matrix.os_type }}-${{ matrix.arch }} container
        # Use docker run to execute a shell command inside the container.
        run: |
          CONTAINER_IMAGE="${{ matrix.os_type == 'manylinux' && 
                             (matrix.arch == 'x86_64' && 'quay.io/pypa/manylinux_2_28_x86_64' || 'quay.io/pypa/manylinux_2_28_aarch64') ||
                             (matrix.arch == 'x86_64' && 'quay.io/pypa/musllinux_1_2_x86_64' || 'quay.io/pypa/musllinux_1_2_aarch64') }}"

          # Set CORE_ARCH variable based on the matrix architecture
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            CORE_ARCH="x86"
          else
            CORE_ARCH="aarch64"
          fi

          # Use a heredoc to create a shell script and pipe it to docker run, passing variables with -e
          docker run --rm \
            -v "$(pwd):/github/workspace" \
            -w /github/workspace \
            -e "TAG=${{ needs.prepare.outputs.tag }}" \
            -e "CORE_ARCH=${CORE_ARCH}" \
            -e "OS_TYPE=${{ matrix.os_type }}" \
            "$CONTAINER_IMAGE" sh -c "
            set -e

            # Install dependencies
            if [ \"\$OS_TYPE\" = \"manylinux\" ]; then
              yum update -y
              yum install -y jq zip
            elif [ \"\$OS_TYPE\" = \"musllinux\" ]; then
              apk update
              apk add jq zip
            fi

            # Download release tarball
            url=\"https://github.com/opengrep/opengrep/releases/download/\$TAG/opengrep_core-linux_\$CORE_ARCH.tar.gz\"
            echo \"Downloading \$url\"
            curl -L -f \"\$url\" -o \"opengrep_core-linux_\$CORE_ARCH.tar.gz\"

            # Extract tarball
            tar -xzf \"opengrep_core-linux_\$CORE_ARCH.tar.gz\"
            ls -lah

            # Install Python and pip
            if [ \"\$OS_TYPE\" = \"manylinux\" ]; then
              # manylinux comes with pre-installed Pythons in /opt/python
              /opt/python/cp39-cp39/bin/pip install --force-reinstall setuptools wheel twine
            elif [ \"\$OS_TYPE\" = \"musllinux\" ]; then
              # musllinux requires installing python and pip
              apk add python3-dev
              python3 -m pip install --force-reinstall setuptools wheel twine
            fi

            # Create the necessary directory before moving the file
            mkdir -p cli/src/semgrep/bin
            
            # move opengrep-core to bin directory and fix permissions
            mv opengrep-core cli/src/semgrep/bin
            chmod +x ./scripts/build-wheels.sh
            ./scripts/build-wheels.sh

            # Test package
            if [ \"\$OS_TYPE\" = \"manylinux\" ]; then
              /opt/python/cp39-cp39/bin/pip install --force-reinstall cli/dist/*.whl
              export PATH=/opt/python/cp39-cp39/bin:\$PATH
            elif [ \"\$OS_TYPE\" = \"musllinux\" ]; then
              python3 -m pip install --force-reinstall cli/dist/*.whl
              export PATH=/usr/bin:\$PATH
            fi
            
            echo '1 == 1' | opengrep -l python -e '\$X == \$X'
            opengrep --version
          "

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os_type }}-${{ matrix.arch }}-wheels
          path: cli/dist.zip
